from env_gateway_sdk import EnvClient, GatewayClient
print("Creating gateway client...")
gateway_client = GatewayClient(base_url="http://env-gateway.ailab.ailab.ai",key="huangha-kdio28HD")
print("\nCreating environment...")
env = gateway_client.create(image_tag="hb_3d-scan-calc", ttl_seconds=1800)
print(env.env_id, env.url)
print("\nCreating environment client...")
env_client = EnvClient(env.url)
print(env_client.status())
print(env_client.heartbeat())
print("\nStarting keepalive...")
env_client.keepalive(in_secs=10)  # 立即返回，后台线程持续发送心跳
print("\nChecking health...")
print(env_client.health())
print("\nExecuting command...")
print(env_client.exec("pwd"))
print("\nUploading text...")
print(env_client.upload_text("/tmp/hello.txt", "hello"))
print("\nDownloading file...")
downloaded = env_client.download_file("/tmp/hello.txt")
print(downloaded.content.decode())
# GatewayClient.close(env_id) 负责关闭远端环境，而 EnvClient.close() 负责停止本地 EnvClient 持有的后台 keepalive 线程，等同于关闭本地环境客户端。
print("\nClosing environment client...")
env_client.close()
print("\nClosing environment...")
print(gateway_client.close(env.env_id))